import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import "swiper/css";
import { StoreProvider } from "./StoreProvider";
import { Toaster } from "@/components/ui/sonner";
import QueryContextProvider from "./query.context.provider";
import { Suspense } from "react";

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        <Suspense fallback={<div>Loading</div>}>
          <StoreProvider>
            <QueryContextProvider>
              <main>{children}</main>
              <Toaster />
            </QueryContextProvider>
          </StoreProvider>
        </Suspense>
      </body>
    </html>
  );
}
